-- ICD-10-CM sample codes (100) curated from chapters at
-- https://www.icd10data.com/ICD10CM/Codes
INSERT OR IGNORE INTO diagnoses (code, description) VALUES
('A09', 'Infectious gastroenteritis and colitis, unspecified'),
('A15.0', 'Tuberculosis of lung'),
('A41.9', 'Sepsis, unspecified organism'),
('A49.9', 'Bacterial infection, unspecified'),
('B00.9', 'Herpesviral infection, unspecified'),
('B18.2', 'Chronic viral hepatitis C'),
('B20', 'Human immunodeficiency virus [HIV] disease'),
('B34.9', 'Viral infection, unspecified'),
('B35.1', 'Tinea unguium'),
('B37.9', 'Candidiasis, unspecified'),
('C34.90', 'Malignant neoplasm of unspecified part of unspecified bronchus or lung'),
('C50.919', 'Malignant neoplasm of unspecified site of unspecified female breast'),
('C61', 'Malignant neoplasm of prostate'),
('C73', 'Malignant neoplasm of thyroid gland'),
('C78.00', 'Secondary malignant neoplasm of unspecified lung'),
('D50.9', 'Iron deficiency anemia, unspecified'),
('D64.9', 'Anemia, unspecified'),
('D69.6', 'Thrombocytopenia, unspecified'),
('E03.9', 'Hypothyroidism, unspecified'),
('E05.90', 'Thyrotoxicosis, unspecified without thyrotoxic crisis or storm'),
('E10.9', 'Type 1 diabetes mellitus without complications'),
('E11.9', 'Type 2 diabetes mellitus without complications'),
('E11.65', 'Type 2 diabetes mellitus with hyperglycemia'),
('E66.9', 'Obesity, unspecified'),
('E78.5', 'Hyperlipidemia, unspecified'),
('E87.1', 'Hypo-osmolality and hyponatremia'),
('F10.10', 'Alcohol abuse, uncomplicated'),
('F17.210', 'Nicotine dependence, cigarettes, uncomplicated'),
('F32.9', 'Major depressive disorder, single episode, unspecified'),
('F41.1', 'Generalized anxiety disorder'),
('F41.9', 'Anxiety disorder, unspecified'),
('F43.10', 'Post-traumatic stress disorder, unspecified'),
('F90.9', 'Attention-deficit hyperactivity disorder, unspecified type'),
('G40.909', 'Epilepsy, unspecified, not intractable, without status epilepticus'),
('G43.909', 'Migraine, unspecified, not intractable, without status migrainosus'),
('G47.00', 'Insomnia, unspecified'),
('G89.29', 'Other chronic pain'),
('H10.9', 'Unspecified conjunctivitis'),
('H25.9', 'Unspecified age-related cataract'),
('H40.9', 'Unspecified glaucoma'),
('H52.1', 'Myopia'),
('H61.23', 'Impacted cerumen, bilateral'),
('H66.90', 'Otitis media, unspecified, unspecified ear'),
('I10', 'Essential (primary) hypertension'),
('I20.9', 'Angina pectoris, unspecified'),
('I21.9', 'Acute myocardial infarction, unspecified'),
('I25.10', 'Atherosclerotic heart disease of native coronary artery without angina pectoris'),
('I48.91', 'Unspecified atrial fibrillation'),
('I50.9', 'Heart failure, unspecified'),
('I63.9', 'Cerebral infarction, unspecified'),
('I80.3', 'Phlebitis and thrombophlebitis of lower extremities, unspecified'),
('J02.9', 'Acute pharyngitis, unspecified'),
('J06.9', 'Acute upper respiratory infection, unspecified'),
('J18.9', 'Pneumonia, unspecified organism'),
('J20.9', 'Acute bronchitis, unspecified'),
('J30.9', 'Allergic rhinitis, unspecified'),
('J44.9', 'Chronic obstructive pulmonary disease, unspecified'),
('J45.909', 'Unspecified asthma, uncomplicated'),
('K21.9', 'Gastro-esophageal reflux disease without esophagitis'),
('K29.70', 'Gastritis, unspecified, without bleeding'),
('K35.80', 'Unspecified acute appendicitis'),
('K40.90', 'Unilateral inguinal hernia, without obstruction or gangrene, not specified as recurrent'),
('K52.9', 'Noninfective gastroenteritis and colitis, unspecified'),
('K57.30', 'Diverticulosis of large intestine without perforation or abscess without bleeding'),
('K58.9', 'Irritable bowel syndrome without diarrhea'),
('K80.20', 'Calculus of gallbladder without cholecystitis without obstruction'),
('L03.90', 'Cellulitis, unspecified'),
('L20.9', 'Atopic dermatitis, unspecified'),
('L30.9', 'Dermatitis, unspecified'),
('L40.0', 'Psoriasis vulgaris'),
('L50.9', 'Urticaria, unspecified'),
('M06.9', 'Rheumatoid arthritis, unspecified'),
('M17.9', 'Osteoarthritis of knee, unspecified'),
('M19.90', 'Unspecified osteoarthritis, unspecified site'),
('M25.50', 'Pain in unspecified joint'),
('M54.5', 'Low back pain'),
('M54.2', 'Cervicalgia'),
('M79.3', 'Panniculitis, unspecified'),
('M79.603', 'Pain in unspecified arm'),
('N18.3', 'Chronic kidney disease, stage 3 (moderate)'),
('N18.9', 'Chronic kidney disease, unspecified'),
('N20.0', 'Calculus of kidney'),
('N30.00', 'Acute cystitis without hematuria'),
('N39.0', 'Urinary tract infection, site not specified'),
('N40.0', 'Benign prostatic hyperplasia without lower urinary tract symptoms'),
('N92.6', 'Irregular menstruation, unspecified'),
('O80', 'Encounter for full-term uncomplicated delivery'),
('R05.9', 'Cough, unspecified'),
('R06.02', 'Shortness of breath'),
('R07.9', 'Chest pain, unspecified'),
('R10.9', 'Unspecified abdominal pain'),
('R11.2', 'Nausea with vomiting, unspecified'),
('R19.7', 'Diarrhea, unspecified'),
('R50.9', 'Fever, unspecified'),
('R51.9', 'Headache, unspecified'),
('R53.83', 'Other fatigue'),
('Z00.00', 'Encounter for general adult medical examination without abnormal findings'),
('Z23', 'Encounter for immunization'),
('Z51.11', 'Encounter for antineoplastic chemotherapy'),
('Z79.4', 'Long term (current) use of insulin');
